name: 'CodeStats - Readme'
author: André Lademann
description: 'Add a codestats coding activity graph in your readme file.'

inputs:
  GIT_USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false

  CODESTATS_USERNAME:
    description: 'Your codestats username.'
    required: true

  COMMIT_MESSAGE:
    description: 'Add a commit message of your choice.'
    default: 'Update the graph with new CodeStats metrics.'
    required: false


  SHOW_TITLE:
    description: 'Show a title with a Date.'
    required: false

  SHOW_LINK:
    description: 'Displayes a link to your codestat profile.'
    required: false
  
  GRAPH_WIDTH:
    description: 'The width of the graph. [default: 42].'
    default: '42'
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'info'
  color: 'blue'
