name: 'CodeStats - Readme'
author: André Lademann
description: 'Add a codestats coding activity graph in your readme file.'

inputs:

  GITHUB_USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false

  CODESTATS_USERNAME:
    description: 'Your codestats username.'
    required: true

  COMMIT_MESSAGE:
    description: "Add a commit message of your choice."
    default: "Update the graph with new CodeStat metrics."
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'info'
  color: 'blue'
