name: 'CodeStats - Readme'
author: André Lademann
description: 'Add a codestats coding activity graph in your readme file.'

inputs:
  GITHUB_USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false
  GITHUB_TOKEN:
    description: 'Your GitHub toben'
    default: ${{ github.token }}
    required: false

  CODESTATS_USERNAME:
    description: 'Your codestats username.'
    required: true

  COMMIT_MESSAGE:
    description: 'Add a commit message of your choice.'
    default: 'Update the graph with new CodeStats metrics.'
    required: false

  SHOW_TITLE:
    description: 'Show a title with a Date.'
    required: false

  DEBUG:
    description: 'Debug theaction'
    required: false

  SHOW_LINK:
    description: 'Displayes a link to your codestat profile.'
    required: false

  GRAPH_WIDTH:
    description: 'The width of the graph. [default: 42].'
    default: '42'
    required: false

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
runs:
  using: 'node12'
  pre: 'npm install'
  main: 'index.js'

branding:
  icon: 'info'
  color: 'blue'
